# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QsJp4q4hjQilWq38uwons7MRMKbGtZ7
"""

from google.colab import files
uploaded = files.upload()

!pip install -q pytorch-tabnet onnx onnx2tf onnx_graphsurgeon sng4onnx onnxsim

"""
Convert the trained pytorch-tabnet regressor (tabnet_model.zip) into a
.tflite file that lib/services/tflite_service.dart can load.

Updated version: includes the dynamo=False / opset_version=17 fix
already validated against this exact architecture (input_dim=14,
output_dim=1, no categorical embeddings, entmax masking - confirmed via
model_params.json) - so this should convert cleanly without hitting the
ONNX export crash from before.

RUN THIS IN COLAB (or wherever you trained the model) - NOT on a
disk/RAM-constrained machine. PyTorch + TensorFlow + the ONNX toolchain
together need a few GB.

Usage in Colab:
    1. Upload the new tabnet_model.zip to the Colab session
       (from google.colab import files; files.upload()).
    2. pip install the packages in the first cell below.
    3. Run the rest of the cells top to bottom.
    4. Download tabnet_model.tflite at the end and drop it into
       heartsense_ai/assets/models/tabnet_model.tflite (overwriting the
       old, incorrect one).
"""

# 1) Install dependencies -----------------------------------------------
# !pip install -q pytorch-tabnet torch onnx onnx2tf onnx_graphsurgeon sng4onnx onnxsim tensorflow

import numpy as np
import pandas as pd
import torch
from pytorch_tabnet.tab_model import TabNetRegressor

# 2) Load the trained TabNet model ---------------------------------------
model = TabNetRegressor()
model.load_model("tabnet_model.zip")  # adjust path if needed

# IMPORTANT: TabNetRegressor.network.forward() returns (output, M_loss).
# We only want the prediction, so wrap it in a module that returns a single
# tensor - this also makes the resulting ONNX/TFLite graph simpler.
class TabNetWrapper(torch.nn.Module):
    def __init__(self, tabnet_network):
        super().__init__()
        self.tabnet_network = tabnet_network

    def forward(self, x):
        out, _ = self.tabnet_network(x)
        return out

wrapper = TabNetWrapper(model.network)
wrapper.eval()

NUM_FEATURES = 14  # sex, age, cp, resting_BP, chol, fbs, restecg, thalach,
                    # exang, oldpeak, slope, ca, thal, Max Heart Rate Reserve
dummy_input = torch.randn(1, NUM_FEATURES, dtype=torch.float32)

# 3) Export to ONNX -------------------------------------------------------
# NOTE: dynamo=False + opset_version=17 is required here - the newer
# "dynamo" ONNX exporter (PyTorch's default since ~2.x) fails on TabNet's
# internal ops (hits a constant-folding crash on a SplitToSequence node
# from the entmax/sparsemax masking). Forcing the older TorchScript-based
# exporter avoids that entirely. This was verified working on the
# previous tabnet_model.zip checkpoint - same architecture here, so it
# should convert the same way.
torch.onnx.export(
    wrapper,
    dummy_input,
    "tabnet_model.onnx",
    input_names=["input"],
    output_names=["risk_score"],
    dynamic_axes={"input": {0: "batch"}, "risk_score": {0: "batch"}},
    opset_version=17,
    dynamo=False,
)
print("ONNX export done: tabnet_model.onnx")

# 4) Convert ONNX -> TensorFlow SavedModel -> TFLite ---------------------
# onnx2tf is the actively-maintained tool for this (better op coverage
# than the older onnx-tf). Run from a shell cell in Colab:
#   !onnx2tf -i tabnet_model.onnx -o tabnet_saved_model
#
# This produces several .tflite variants inside tabnet_saved_model/.
# Use the plain float32 one, usually named:
#   tabnet_saved_model/tabnet_model_float32.tflite
# Rename it to tabnet_model.tflite before dropping it into the Flutter
# project's assets/models/ folder.

# 5) Sanity check: compare PyTorch vs TFLite outputs on real data --------
# Run this AFTER you have the .tflite file, to make sure the conversion
# didn't change the model's behavior.
def sanity_check(tflite_path, test_scaled_csv):
    import tensorflow as tf

    df = pd.read_csv(test_scaled_csv)
    X = df.drop(columns=["Heart Disease Risk Score"]).values.astype(np.float32)
    y = df["Heart Disease Risk Score"].values

    # PyTorch predictions
    torch_preds = model.predict(X).flatten()

    # TFLite predictions
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    out = interpreter.get_output_details()[0]

    tflite_preds = []
    for row in X:
        interpreter.set_tensor(inp["index"], row.reshape(1, -1))
        interpreter.invoke()
        tflite_preds.append(interpreter.get_tensor(out["index"]).flatten()[0])
    tflite_preds = np.array(tflite_preds)

    diff = np.abs(torch_preds - tflite_preds)
    print("Max abs diff  PyTorch vs TFLite:", diff.max())
    print("Mean abs diff PyTorch vs TFLite:", diff.mean())
    print("Sample compare (first 5):")
    for i in range(5):
        print(f"  actual={y[i]:.2f}  torch={torch_preds[i]:.2f}  tflite={tflite_preds[i]:.2f}")

# Example:
# sanity_check("tabnet_saved_model/tabnet_model_float32.tflite", "dataset/test_scaled.csv")

!onnx2tf -i tabnet_model.onnx -o tabnet_saved_model
!ls tabnet_saved_model

import glob, shutil
candidates = glob.glob("tabnet_saved_model/*float32*.tflite")
print(candidates)
shutil.copy(candidates[0], "tabnet_model.tflite")

sanity_check("tabnet_model.tflite", "test_scaled.csv")

from google.colab import files
files.download("tabnet_model.tflite")